# ENVIRONMENT VARIABLES
DOMAIN: ""
SENDER_EMAIL: "printex.test@gmail.com"
MAILER_DOMAIN: "gmail.com"
SMTP_SERVER: "smtp.gmail.com"
SMTP_PORT: 587
SMTP_USER: "printex.test"
SMTP_PWD: "printex121"
