development:
  adapter: postgresql
  host: localhost
  username: user
  password: 1234
  database: app-dev

test:
  adapter: postgresql
  host: localhost
  username: user
  password: 1234
  database: app-test

production:
  adapter: postgresql
  host: localhost
  username: user
  password: 1234
  database: app-production
